### ISSUE TITLE
Add font smoothing

### ISSUE THREAD

**Issue by veloxy** [veloxy/sourcebox#13]
``` css
body {
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
}
```
